#!/bin/bash

set -xe
DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo ${DIR}
# Plugins need to have their absolute paths supplied
# 
PROTOC_PLUGIN=$(which protoc-gen-fabart)

# run the protoc tool to parse the proto files, ensures everything is correct
# outdirectory supplied, with possible options  (for illustration currently)
protoc --plugin="${PROTOC_PLUGIN}" -I ${DIR}/proto ${DIR}/proto/AssetTransfer.proto  --fabart_out=json=y:${DIR}/generated

# run the template generation side of the plugin here
#DEBUG=* fabart create --localfile ${DIR}/generated/assettransfer-md.json --outputdir ${DIR}/generated/ --template contract_ts domain_adts_ts domain_adts_java client_java
DEBUG=* fabart create --localfile ${DIR}/generated/assettransfer-md.json --outputdir ${DIR}/generated/ --template  contract_ts domain_adts_ts
